apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-telemetry-operator
subjects:
- kind: ServiceAccount
  name: service-telemetry-operator
roleRef:
  kind: Role
  name: service-telemetry-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-telemetry-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: service-telemetry-operator-cluster
subjects:
- kind: ServiceAccount
  name: service-telemetry-operator
  namespace: service-telemetry
